//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anna
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheTurnoverOfBooks
    {
        public int IssueId { get; set; }
        public int UsersId { get; set; }
        public int BooksId { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public Nullable<System.DateTime> ReturnDateActual { get; set; }
        public System.DateTime ReturnDateForFormal { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
