//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace localMovieViewingHistory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tours()
        {
            this.Travel_Packeges = new HashSet<Travel_Packeges>();
        }
    
        public int id_tours { get; set; }
        public Nullable<int> id_countries { get; set; }
        public Nullable<System.DateTime> start_tours { get; set; }
        public Nullable<System.DateTime> end_tours { get; set; }
        public Nullable<int> quantity { get; set; }
        public string title_tours { get; set; }
    
        public virtual Countries Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Travel_Packeges> Travel_Packeges { get; set; }
    }
}
