//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace localMovieViewingHistory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel_Packeges
    {
        public Nullable<int> id_customers { get; set; }
        public Nullable<int> id_tours { get; set; }
        public int id_travel_packeges { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Tours Tours { get; set; }
    }
}
