USE [master]
GO
/****** Object:  Database [TA]    Script Date: 02.02.2021 11:40:20 ******/
CREATE DATABASE [TA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TA] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TA] SET ARITHABORT OFF 
GO
ALTER DATABASE [TA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TA] SET RECOVERY FULL 
GO
ALTER DATABASE [TA] SET  MULTI_USER 
GO
ALTER DATABASE [TA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TA] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'TA', N'ON'
GO
ALTER DATABASE [TA] SET QUERY_STORE = OFF
GO
USE [TA]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [TA]
GO
/****** Object:  Table [dbo].[Countries]    Script Date: 02.02.2021 11:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Countries](
	[id_countries] [int] NOT NULL,
	[title] [nvarchar](50) NULL,
 CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED 
(
	[id_countries] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 02.02.2021 11:40:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[id_customers] [int] NOT NULL,
	[series_pass] [int] NULL,
	[surname] [nvarchar](50) NULL,
	[name] [nvarchar](50) NULL,
	[middle_name] [nvarchar](50) NULL,
	[date_of_birth] [date] NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[id_customers] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tours]    Script Date: 02.02.2021 11:40:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tours](
	[id_tours] [int] NOT NULL,
	[id_countries] [int] NULL,
	[start_tours] [date] NULL,
	[end_tours] [date] NULL,
	[quantity] [int] NULL,
	[title_tours] [nvarchar](50) NULL,
	[price] [int] NULL,
 CONSTRAINT [PK_Tours] PRIMARY KEY CLUSTERED 
(
	[id_tours] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Travel_Packeges]    Script Date: 02.02.2021 11:40:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Travel_Packeges](
	[id_travel_packeges] [int] NOT NULL,
	[id_customers] [int] NULL,
	[id_tours] [int] NULL,
 CONSTRAINT [PK_TravelAgent] PRIMARY KEY CLUSTERED 
(
	[id_travel_packeges] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tours]  WITH CHECK ADD  CONSTRAINT [FK_Tours_Countries] FOREIGN KEY([id_countries])
REFERENCES [dbo].[Countries] ([id_countries])
GO
ALTER TABLE [dbo].[Tours] CHECK CONSTRAINT [FK_Tours_Countries]
GO
ALTER TABLE [dbo].[Travel_Packeges]  WITH CHECK ADD  CONSTRAINT [FK_Travel_Packeges_Customer] FOREIGN KEY([id_customers])
REFERENCES [dbo].[Customer] ([id_customers])
GO
ALTER TABLE [dbo].[Travel_Packeges] CHECK CONSTRAINT [FK_Travel_Packeges_Customer]
GO
ALTER TABLE [dbo].[Travel_Packeges]  WITH CHECK ADD  CONSTRAINT [FK_Travel_Packeges_Tours1] FOREIGN KEY([id_tours])
REFERENCES [dbo].[Tours] ([id_tours])
GO
ALTER TABLE [dbo].[Travel_Packeges] CHECK CONSTRAINT [FK_Travel_Packeges_Tours1]
GO
USE [master]
GO
ALTER DATABASE [TA] SET  READ_WRITE 
GO
