USE [master]
GO

/****** Object:  Database [ TA]    Script Date: 31.01.2021 21:47:33 ******/
CREATE DATABASE [ TA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N' ta', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ ta.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N' ta_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ ta_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ TA] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ TA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ TA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ TA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ TA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ TA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ TA] SET ARITHABORT OFF 
GO

ALTER DATABASE [ TA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ TA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ TA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ TA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ TA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ TA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ TA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ TA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ TA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ TA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ TA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ TA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ TA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ TA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ TA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ TA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ TA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ TA] SET RECOVERY FULL 
GO

ALTER DATABASE [ TA] SET  MULTI_USER 
GO

ALTER DATABASE [ TA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ TA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ TA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ TA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ TA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ TA] SET QUERY_STORE = OFF
GO

USE [ TA]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ TA] SET  READ_WRITE 
GO


USE [ TA]
GO

/****** Object:  Table [dbo].[Counries]    Script Date: 31.01.2021 21:52:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Counries](
	[id_countries] [int] NOT NULL,
	[title] [nvarchar](50) NULL,
 CONSTRAINT [PK_Counries] PRIMARY KEY CLUSTERED 
(
	[id_countries] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ TA]
GO

/****** Object:  Table [dbo].[Customers]    Script Date: 31.01.2021 21:52:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customers](
	[id_customers] [int] NOT NULL,
	[series_pass] [int] NULL,
	[surename] [nvarchar](50) NULL,
	[name] [nvarchar](50) NULL,
	[middle_name] [nvarchar](50) NULL,
	[date_of_birth] [date] NULL,
	[number_pass] [int] NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[id_customers] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ TA]
GO

/****** Object:  Table [dbo].[Tours]    Script Date: 31.01.2021 21:53:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tours](
	[id_tours] [int] NOT NULL,
	[id_countres] [int] NULL,
	[start_tour] [date] NULL,
	[end_tour] [date] NULL,
	[quantity] [int] NULL,
 CONSTRAINT [PK_Tours] PRIMARY KEY CLUSTERED 
(
	[id_tours] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ TA]
GO

/****** Object:  Table [dbo].[TravelPackeges]    Script Date: 31.01.2021 21:53:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TravelPackeges](
	[id_travel_packeges] [int] NOT NULL,
	[id_customers] [int] NULL,
	[id_tours] [int] NULL,
 CONSTRAINT [PK_TravelPackeges] PRIMARY KEY CLUSTERED 
(
	[id_travel_packeges] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TravelPackeges]  WITH CHECK ADD  CONSTRAINT [FK_TravelPackeges_Customers] FOREIGN KEY([id_customers])
REFERENCES [dbo].[Customers] ([id_customers])
GO

ALTER TABLE [dbo].[TravelPackeges] CHECK CONSTRAINT [FK_TravelPackeges_Customers]
GO

ALTER TABLE [dbo].[TravelPackeges]  WITH CHECK ADD  CONSTRAINT [FK_TravelPackeges_Tours] FOREIGN KEY([id_customers])
REFERENCES [dbo].[Tours] ([id_tours])
GO

ALTER TABLE [dbo].[TravelPackeges] CHECK CONSTRAINT [FK_TravelPackeges_Tours]
GO


