USE [master]
GO

/****** Object:  Database [ travel agent]    Script Date: 30.01.2021 14:16:01 ******/
CREATE DATABASE [ travel agent]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N' travel agent', FILENAME = N'C:\Users\Анна\Desktop\Кошолапова Анна 305\ travel agent.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N' travel agent_log', FILENAME = N'C:\Users\Анна\Desktop\Кошолапова Анна 305\ travel agent_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ travel agent] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ travel agent].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ travel agent] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ travel agent] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ travel agent] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ travel agent] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ travel agent] SET ARITHABORT OFF 
GO

ALTER DATABASE [ travel agent] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ travel agent] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ travel agent] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ travel agent] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ travel agent] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ travel agent] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ travel agent] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ travel agent] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ travel agent] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ travel agent] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ travel agent] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ travel agent] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ travel agent] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ travel agent] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ travel agent] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ travel agent] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ travel agent] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ travel agent] SET RECOVERY FULL 
GO

ALTER DATABASE [ travel agent] SET  MULTI_USER 
GO

ALTER DATABASE [ travel agent] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ travel agent] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ travel agent] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ travel agent] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ travel agent] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ travel agent] SET QUERY_STORE = OFF
GO

USE [ travel agent]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ travel agent] SET  READ_WRITE 
GO


USE [ travel agent]
GO

/****** Object:  Table [dbo].[Countries]    Script Date: 30.01.2021 14:16:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Countries](
	[id_countries] [int] NOT NULL,
	[title] [nvarchar](50) NULL,
 CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED 
(
	[id_countries] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [ travel agent]
GO

/****** Object:  Table [dbo].[Customers]    Script Date: 30.01.2021 14:16:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customers](
	[id_customers] [int] NOT NULL,
	[nickname] [nvarchar](50) NULL,
	[series_and_number] [int] NULL,
	[surname] [nvarchar](50) NULL,
	[name] [nvarchar](50) NULL,
	[middle_name] [nvarchar](50) NULL,
	[date_of_birth] [date] NULL,
 CONSTRAINT [PK_Customers_1] PRIMARY KEY CLUSTERED 
(
	[id_customers] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ travel agent]
GO

/****** Object:  Table [dbo].[Tours]    Script Date: 30.01.2021 14:17:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tours](
	[id_tours] [int] NOT NULL,
	[id_customers] [int] NULL,
	[id_countries] [int] NULL,
	[start_tour] [date] NULL,
	[end_tour] [date] NULL,
	[quantity] [int] NULL,
 CONSTRAINT [PK_Tours] PRIMARY KEY CLUSTERED 
(
	[id_tours] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Tours]  WITH CHECK ADD  CONSTRAINT [FK_Tours_Countries] FOREIGN KEY([id_countries])
REFERENCES [dbo].[Countries] ([id_countries])
GO

ALTER TABLE [dbo].[Tours] CHECK CONSTRAINT [FK_Tours_Countries]
GO

ALTER TABLE [dbo].[Tours]  WITH CHECK ADD  CONSTRAINT [FK_Tours_Customers] FOREIGN KEY([id_customers])
REFERENCES [dbo].[Customers] ([id_customers])
GO

ALTER TABLE [dbo].[Tours] CHECK CONSTRAINT [FK_Tours_Customers]
GO



